### ISSUE TITLE
COMPILE PITY COMPILE PITY COMPILE PITY COMPILE PITY COMPILE PITY COMPILE PITY COMPILE PITY 

### ISSUE THREAD

**Issue by Soraiko** [mtrebi/ImagesPrimitives#1]
YOU GUYS KNOW THE PAIN OF SPENDING HOURS AND HOURS TRYING TO RUN SOMEONE ELSE'S PROJECT
WHY DO YOU LOVE TO DO THAT PAIN TO OTHER PEOPLE YOU ASSHOLES 
IM FUCKING TIRED OF EVERYONE ON THIS FUCKING EARTH BEING THE EXACT SAME COPY PASTE ASSHOLE OF EVERYONE ELSE
ZERO EMPATHY NOTHING
ALL THE SAME

IM BLOWING MY FUSE BECAUSE I KNOW YOU WILL NEVER ANSWER THIS LIKE EVERY OTHER FUCKING THOUSAND OF BILLIONS MESSAGES I SENT WITHOUT REPLY SINCE THE TEN FUCKING YEARS MY GITHUB ACCOUNT EXISTS

**Comment by mtrebi** [comment]
If you had posted the compilation errors instead of ranting you would have maybe received more help.
